### ISSUE TITLE
using arrow function,this keyword and classes in place of normal function

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#168]
we should update contributing guidelines to use [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [this keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) and [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields)  over traditional function as they provide some good features of  ECMAScript, provide more readability and allow a user to write less code.

[12 Reasons Why ES6 is the future of JavaScript and Web Development](http://blog.thefirehoseproject.com/posts/12-reasons-es6-future-javascript-web-development/)

**Comment by itsvinayak** [comment]
@cclauss

**Comment by cclauss** [comment]
I am not an active JavaScript developer.  I can say that in Python, there is a movement away from classes (trying to do more in functions and less in OOP) and away from anonymous functions because normal functions are easier to understand (more self-documenting) and easier to test.

Hopefully active JavaScript developers can jump into this discussion and provide proper feedback.

**Comment by ayaankhan98** [comment]
it is not always necessary to use arrow funtions because along with benefits there are pitfalls also if one is not carefull about using them such as the `this` keyword behaves differently with normal functions and arrow functions.
i think the best is to use normal functions for object methods and use arrow functions for callbacks or methods like map, reduce, or forEach.

**Comment by itsvinayak** [comment]
@ayaankhan98, this issue is on hold for a long time should we close it (if not needed) or wait for other members to review

**Comment by ayaankhan98** [comment]
let's close this and let the contributor to decided the best possible design for the program let it be up to them to use arrow functions or calsses what we can do is that if something is not fine or if there is some another way to do that thing in more efficient way then we can ask them to change the implementation.
