### ISSUE TITLE
Remove redundant `Find-broken-doctest` branch

### ISSUE THREAD

**Issue by raklaptudirm** [TheAlgorithms/Javascript#973]
@cclauss There was an issue with doctests failing some time ago when you created the `Find-broken-doctest`(#543) branch to fix it. Since then, we have completely switched over to `jest`(#742) for testing and this is no longer an issue. However, the branch is still present in this repository and I do not have the perms to remove it.

**Comment by hamidreza-hz98** [comment]
please unsubscribe me from everything -------- Original message --------From: Rak Laptudirm ***@***.***>Date: Sun, Apr 3, 2022, 12:03 PMTo: TheAlgorithms/Javascript ***@***.***>Cc: Subscribed ***@***.***>Subject: [TheAlgorithms/Javascript] Remove redundant `Find-broken-doctest` branch (Issue #973)
@cclauss There was an issue with doctests failing some time ago when you created the Find-broken-doctest(#543) branch to fix it. Since then, we have completely switched over to jest(#742) for testing and this is no longer an issue. However, the branch is still present in this repository and I do not have the perms to remove it.
